#!/bin/sh

##############################################
# Runs CCPA Gempak processing on 6 file types
##############################################

set -xa
# ################################
# SET SHELL PROCESSING VARIABLES
# ################################
export PS4='$SECONDS + '
date
#
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

#
# Set up model and cycle specific variables
#
export NET=${NET:-ccpa}
export RUN=${RUN:-ccpa}

export DBN_ALERT_TYPE=CCPA_GEMPAK

export HOMEccpa=${HOMEccpa:-$NWROOT/ccpa.${ccpa_ver}}

#
# Now set up GEMPAK/NTRANS environment
#
#. /nwprod/gempak/.gempak

###################################
# Set up the UTILITIES
###################################
#module load grib_util/v1.0.1

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export PDYm8=`finddate.sh $PDY d-8`
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}}
#export COMOUT=${COMOUT:-${COMROOT}/nawips/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOTp3}/${NET}/${envir}/${RUN}.${PDY}/gempak}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

########################################################
# Execute the script.
  $HOMEccpa/scripts/exccpa_gempak.sh.ecf
########################################################

cat $pgmout

cd ${DATAROOT}
if [ $KEEPDATA != 'YES' ]; then
  rm -rf $DATA
fi
date
